# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rlm',
                'doc_host': 'https://LA3D.github.io',
                'git_url': 'https://github.com/LA3D/rlm',
                'lib_path': 'rlm'},
  'syms': {'rlm.core': {'rlm.core.foo': ('core.html#foo', 'rlm/core.py')}}}
