# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rlm',
                'doc_host': 'https://LA3D.github.io',
                'git_url': 'https://github.com/LA3D/rlm',
                'lib_path': 'rlm'},
  'syms': { 'rlm.core': { 'rlm.core._query_one': ('core.html#_query_one', 'rlm/core.py'),
                          'rlm.core.exec_code': ('core.html#exec_code', 'rlm/core.py'),
                          'rlm.core.in_solveit': ('core.html#in_solveit', 'rlm/core.py'),
                          'rlm.core.llm_query': ('core.html#llm_query', 'rlm/core.py'),
                          'rlm.core.llm_query_batched': ('core.html#llm_query_batched', 'rlm/core.py'),
                          'rlm.core.rlm_run': ('core.html#rlm_run', 'rlm/core.py')},
            'rlm.swtools': {'rlm.swtools.sparql_query': ('swtools.html#sparql_query', 'rlm/swtools.py')}}}
