"""Semantic Webby tool functionality for RLM using dialoghelper inspecttools and core"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_swtools.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/01_swtools.ipynb 2
from .core import *
from sparqlx import *
