"""Semantic Webby tool functionality for RLM using dialoghelper inspecttools and core"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_swtools.ipynb.

# %% auto 0
__all__ = ['sparql_query']

# %% ../nbs/01_swtools.ipynb 2
from .core import *
from .core import rlm_run, QueryMetadata
from sparqlx import *
from rdflib import Graph

# %% ../nbs/01_swtools.ipynb 13
def sparql_query(query:str, endpoint:str="https://query.wikidata.org/sparql", max_results:int=100, name:str='res', ns:dict=None, timeout:float=30.0):
    "Execute SPARQL query, store results in namespace, return summary"
    if ns is None: ns = globals()
    headers = {"User-Agent": "SolveitBot/1.0 (https://solveit.fast.ai)"}
    wrapper = SPARQLWrapper(sparql_endpoint=endpoint, client_config=dict(timeout=timeout, headers=headers))
    result = wrapper.query(query, convert=True)
    if isinstance(result, bool): return f"ASK result: {result}"
    if hasattr(result, 'serialize'):
        triples = list(result)[:max_results]
        ns[name] = Graph()
        for t in triples: ns[name].add(t)
        return f"Graph with {len(triples)} triples stored in '{name}'" + (f" (truncated from {len(result)})" if len(result) > max_results else "")
    result = result[:max_results]
    ns[name] = result
    cols = list(result[0].keys()) if result else []
    return f"SELECT result with {len(result)} rows, columns: {cols}, stored in '{name}'"

